kind: Deployment
apiVersion: apps/v1
metadata:
  name: mw-kube-agent-update
  namespace: "NAMESPACE_VALUE"
spec:
  selector:
    matchLabels:
      app: mw-app
  template:
    metadata:
      labels:
        app: mw-app
        k8s-app: mw-app
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoSchedule"
      - operator: "Exists"
        effect: "NoExecute"

      containers:
        - args:
            - mw-agent 
            - update
          env:
            - name: MW_API_URL_FOR_CONFIG_CHECK
              value: https://d772-2401-4900-1f3e-2a95-8e16-cbfd-3b1e-997d.ngrok-free.app
            - name: MW_CONFIG_CHECK_INTERVAL
              value: 60s
            - name: MW_KUBE_CLUSTER_NAME
              value: "MW_KUBE_CLUSTER_NAME_VALUE"
            - name: MW_API_KEY
              value: "MW_API_KEY_VALUE"
          image: ghcr.io/middleware-labs/mw-kube-agent:k8s-deployment-for-yaml
          imagePullPolicy: Always
          name: mw-kube-agent
          securityContext:
            privileged: true
          resources: {}
      imagePullSecrets:
        - name: gh-regcred
      restartPolicy: Always
      serviceAccountName: mw-service-account-update