receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:9319
      http:
        endpoint: 0.0.0.0:9320

  # Scrapping OS metrics (Infra Metrics)
  hostmetrics:
    collection_interval: 5s
    scrapers:
      process:

processors:
  resource:
    attributes:
    - key: mw.account_key
      action: insert
      value: ${MW_API_KEY}

exporters:
  logging:
    loglevel: debug
  otlp/2:
    endpoint: ${TARGET}
    tls:
      insecure: true
    headers:
      authorization: ${MW_API_KEY}

service:
  pipelines:
    metrics:
      receivers: [ hostmetrics, otlp ]
      processors: [ resource ]
      exporters: [ logging, otlp/2 ]