apiVersion: v1
kind: Namespace
metadata:
  name: mw-agent-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: mw-app
  name: mw-service-account
  namespace: mw-agent-ns
---
# This section modified
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: mw-app
  name: mw-service
  namespace: mw-agent-ns
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8443
  selector:
    k8s-app: mw-app
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: mw-app
  name: mw-app-certs
  namespace: mw-agent-ns
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: mw-app
  name: mw-app-csrf
  namespace: mw-agent-ns
type: Opaque
data:
  csrf: ""
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: mw-app
  name: mw-app-key-holder
  namespace: mw-agent-ns
type: Opaque
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    k8s-app: mw-app
  name: mw-app-settings
  namespace: mw-agent-ns
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: mw-app
  name: mw-role
  namespace: mw-agent-ns
rules:
  # Allow Dashboard to get, update and delete Dashboard exclusive secrets.
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["mw-app-key-holder", "mw-app-certs", "mw-app-csrf"]
    verbs: ["get", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "delete", "patch", "create"]
    # Allow Dashboard to get and update 'mw-app-settings' config map.
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["mw-app-settings"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
    # Allow Dashboard to get metrics.
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["heapster", "dashboard-metrics-scraper"]
    verbs: ["proxy"]
  - apiGroups: [""]
    resources: ["services/proxy"]
    resourceNames: ["heapster", "http:heapster:", "https:heapster:", "dashboard-metrics-scraper", "http:dashboard-metrics-scraper"]
    verbs: ["get"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: mw-cluster-role
  namespace: mw-agent-ns
rules:
  # Allow Metrics Scraper to get metrics from the Metrics server
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]

  # Other resources
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods", "serviceaccounts", "services", "configmaps", "endpoints", "persistentvolumeclaims", "replicationcontrollers", "replicationcontrollers/scale", "persistentvolumeclaims", "persistentvolumes", "bindings", "events", "limitranges", "namespaces/status", "pods/log", "pods/status", "replicationcontrollers/status", "resourcequotas", "resourcequotas/status"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments", "deployments/scale", "replicasets", "replicasets/scale", "statefulsets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["extensions"]
    resources: ["daemonsets", "deployments", "deployments/scale", "networkpolicies", "replicasets", "replicasets/scale", "replicationcontrollers/scale"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "volumeattachments"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings", "clusterroles", "roles", "rolebindings", ]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    k8s-app: mw-app
  name: mw-role-binding
  namespace: mw-agent-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mw-role
subjects:
  - kind: ServiceAccount
    name: mw-service-account
    namespace: mw-agent-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mw-app
  namespace: mw-agent-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mw-cluster-role
subjects:
  - kind: ServiceAccount
    name: mw-service-account
    namespace: mw-agent-ns
---
kind: Deployment
apiVersion: apps/v1
metadata:
  creationTimestamp: null
  name: mw-kube-agent
  namespace: mw-agent-ns
spec:
  selector:
    matchLabels:
      app: mw-app
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: mw-app
      creationTimestamp: null
    spec:
      containers:
        - args:
            - api-server
            - start
          env:
            - name: TARGET
              value: "TARGET_VALUE"
            - name: MW_API_KEY
              value: "MW_API_KEY_VALUE"
          image: ghcr.io/middleware-labs/agent-kube-go:dev
          imagePullPolicy: Always
          name: mw-kube-agent
          resources: {}
      imagePullSecrets:
        - name: gh-regcred
      restartPolicy: Always
      serviceAccountName: mw-service-account
